In [28]:
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X, y)
knn.predict([[3, 5, 4, 2]])

array([2])

In [30]:
print("Predicted target name:",
       iris['target_names'][knn.predict([[3, 5, 4, 2]])])

Predicted target name: ['virginica']


In [31]:
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

In [32]:
knn1 = KNeighborsClassifier(n_neighbors=3)
knn1.fit(X, y)
knn1.predict(X_new)

array([1, 1])

In [33]:
print("Predicted target name:",
       iris['target_names'][knn1.predict([[3, 5, 4, 2]])])

Predicted target name: ['versicolor']


In [34]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='lbfgs', max_iter=1000)
lr.fit(X, y)
lr.predict(X_new)

array([0, 0])

In [35]:
print("Predicted target name:",
       iris['target_names'][lr.predict([[3, 5, 4, 2]])])

Predicted target name: ['setosa']
